### PR TITLE
Polish translation of the program

### PR DESCRIPTION
**Pull request by nalfgar**

### CODE REVIEW

**Comment by zvezdochiot** [comment]
Hi @nalfgar .

This is English, not Polish! Trash.

**Comment by nalfgar** [comment]
Hi
I have partially translated the file geo_easy.pl.





czw., 1 gru 2022 o 18:01 звездочёт ***@***.***> napisał(a):

**Comment by zvezdochiot** [comment]
Hi @nalfgar .

:information_source: Translated very little for PR. Increase the amount of translated and repeat PR.

**Comment by nalfgar** [comment]
Ok. Thank you.

**Comment by zsiki** [comment]
Hi @nalfgar,

thanks you volunteering translation. Ask me if you are in trouble.
Carry on!

Zoltan

**Comment by nalfgar** [comment]
Thank you.
Darek

czw., 1 gru 2022 o 20:47 Zoltan Siki ***@***.***> napisał(a):

**Pull request closed without merging**
