### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by nalfgar**
I translated the file from English (geo_easy.eng) to Polish (geo_easy.pl).
It is not perfect but I will work on it.

Darek

### CODE REVIEW

**Comment by zvezdochiot** [comment]
Hi @zsiki .

:warning: 
https://github.com/nalfgar/GeoEasy/blob/3a7aab85102fdcb73ce192494e3b33a36bb3e7d1/src/default.msk#L1-L6
and
https://github.com/nalfgar/GeoEasy/blob/3a7aab85102fdcb73ce192494e3b33a36bb3e7README.md#L40-L48

**Comment by zvezdochiot** [comment]
Hi @nalfgar .

Good work. :+1:

**Comment by zsiki** [comment]
Dear Darek,

thanks for your contribution!
I added your translation to geo_easy.msk, so it is available from GeoEasy. If the language of the operating system is Polish, the geo_easy.pl is used by default (please check it). If you start GeoEasy from the command line like this:
`GeoEasy --lang pl`
the Polish GUI will be used.

There is a message file for com_easy module, too. You can find already a com_easy.pl file in the i18n folder (it contains the English messages). You may add to your next year TODO list to translate it, too. :)

image

Zoltan

**Comment by nalfgar** [comment]
I will also translate the "com_easy.pl" file and  I will correct the "geo_easy.pl".
Happy new year!
Darek

**Comment by zsiki** [comment]
Dear Darek,

I've created a new development version (3.2.2) with the Polish translation, you can test it.
http://digikom.hu/english/geo_easy_e.html

Zoltan

**Pull request merged**
